// <auto-generated />
using System;
using IT3045_Final_Group4.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IT3045_Final_Group4.Migrations.TeamMember
{
    [DbContext(typeof(TeamMemberContext))]
    [Migration("20241204215937_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IT3045_Final_Group4.Models.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CollegeProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearInProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthdate = new DateTime(1992, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Associate of Applied Business in Information Technology",
                            FullName = "Toby Wright",
                            YearInProgram = "Freshman"
                        },
                        new
                        {
                            Id = 2,
                            Birthdate = new DateTime(1995, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Associate of Applied Business in Information Technology",
                            FullName = "John Penn",
                            YearInProgram = "Sophomore"
                        },
                        new
                        {
                            Id = 3,
                            Birthdate = new DateTime(1998, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Clermont Certificate in Information Technology",
                            FullName = "Matt Glazier",
                            YearInProgram = "Sophomore"
                        },
                        new
                        {
                            Id = 4,
                            Birthdate = new DateTime(2005, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Bachelor of Science in Cybersecurity",
                            FullName = "Leslie Alonge",
                            YearInProgram = "Sophomore"
                        },
                        new
                        {
                            Id = 5,
                            Birthdate = new DateTime(1998, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Associate of Applied Business in Information Technology",
                            FullName = "Kellen Hubbard",
                            YearInProgram = "Sophomore"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
