// <auto-generated />
using IT3045_Final_Group4.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IT3045_Final_Group4.Migrations.Game
{
    [DbContext(typeof(GameContext))]
    [Migration("20241205201825_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IT3045_Final_Group4.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Developer")
                        .HasColumnType("nvarchar(max)");
                    
                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Game");

                    b.HasData(
                        new
                        {
                            Id = 1, 
                            Name = "Fallout 3", 
                            Developer = "Bethesda Game Studios", 
                            Genre = "Action RPG", 
                            ReleaseDate = "October 28, 2008"
                        },
                        new
                        {
                            Id = 2, 
                            Name = "Fallout 4", 
                            Developer = "Bethesda Game Studios", 
                            Genre = "Action RPG", 
                            ReleaseDate = "November 10, 2015"
                        },
                        new
                        {
                            Id = 3, 
                            Name = "The Elder Scrolls V: Skyrim", 
                            Developer = "Bethesda Game Studios", 
                            Genre = "Action RPG", 
                            ReleaseDate = "November 11, 2011"
                        },
                        new
                        {
                            Id = 4, 
                            Name = "Baldur's Gate 3", 
                            Developer = "Larian Studios", 
                            Genre = "Adventure RPG", 
                            ReleaseDate = "August 3, 2023"
                        },
                        new
                        {
                            Id = 5, 
                            Name = "Mass Effect 2", 
                            Developer = "Bioware", 
                            Genre = "Action RPG", 
                            ReleaseDate = "January 26, 2010"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
