// <auto-generated />
using IT3045_Final_Group4.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IT3045_Final_Group4.Migrations
{
    [DbContext(typeof(BreakfastFoodContext))]
    [Migration("20241208023705_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IT3045_Final_Group4.Models.BreakfastFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beverage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Popular")
                        .HasColumnType("bit");

                    b.Property<string>("ServingSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FavoriteBreakfastFoods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Beverage = "Orange Juice",
                            Calories = 350,
                            Name = "Pancakes",
                            Popular = true,
                            ServingSize = "Medium"
                        },
                        new
                        {
                            Id = 2,
                            Beverage = "Coffee",
                            Calories = 400,
                            Name = "Waffles",
                            Popular = true,
                            ServingSize = "Large"
                        },
                        new
                        {
                            Id = 3,
                            Beverage = "Tea",
                            Calories = 250,
                            Name = "Omelette",
                            Popular = true,
                            ServingSize = "Small"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
