// <auto-generated />
using IT3045_Final_Group4.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IT3045_Final_Group4.Migrations.TreeTable
{
    [DbContext(typeof(TreeTableContext))]
    [Migration("20241206013237_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IT3045_Final_Group4.Models.TreeTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Birthday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BroughtBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TreeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthday = "1990-05-15",
                            BroughtBy = "Alice",
                            Email = "alice@example.com",
                            Height = 20.5,
                            PhoneNumber = "123-456-7890",
                            TreeType = "Oak"
                        },
                        new
                        {
                            Id = 2,
                            Birthday = "1985-03-20",
                            BroughtBy = "Bob",
                            Email = "bob@example.com",
                            Height = 30.0,
                            PhoneNumber = "987-654-3210",
                            TreeType = "Pine"
                        },
                        new
                        {
                            Id = 3,
                            Birthday = "2000-08-10",
                            BroughtBy = "Charlie",
                            Email = "charlie@example.com",
                            Height = 25.300000000000001,
                            PhoneNumber = "456-789-0123",
                            TreeType = "Maple"
                        },
                        new
                        {
                            Id = 4,
                            Birthday = "1995-12-25",
                            BroughtBy = "David",
                            Email = "david@example.com",
                            Height = 15.699999999999999,
                            PhoneNumber = "321-654-9870",
                            TreeType = "Birch"
                        },
                        new
                        {
                            Id = 5,
                            Birthday = "1988-11-05",
                            BroughtBy = "Eve",
                            Email = "eve@example.com",
                            Height = 18.199999999999999,
                            PhoneNumber = "213-546-7890",
                            TreeType = "Cedar"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
